package com.neusoft.medical.bean;

import java.util.Date;

public class ChargeForm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.charge_form_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer chargeFormId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.registration_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer registrationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.charge_item_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer chargeItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.item_count
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer itemCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.uncharged_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer unchargedNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.made_time
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Date madeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.collector_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer collectorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.not_given_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer notGivenNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.reserve1
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.reserve2
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.charge_form.reserve3
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String reserve3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public ChargeForm(Integer chargeFormId, Integer registrationId, Integer chargeItemId, Integer itemCount, Integer unchargedNums, Date madeTime, Integer valid, Integer departmentId, Integer doctorId, Integer collectorId, Integer notGivenNums, String reserve1, String reserve2, String reserve3) {
        this.chargeFormId = chargeFormId;
        this.registrationId = registrationId;
        this.chargeItemId = chargeItemId;
        this.itemCount = itemCount;
        this.unchargedNums = unchargedNums;
        this.madeTime = madeTime;
        this.valid = valid;
        this.departmentId = departmentId;
        this.doctorId = doctorId;
        this.collectorId = collectorId;
        this.notGivenNums = notGivenNums;
        this.reserve1 = reserve1;
        this.reserve2 = reserve2;
        this.reserve3 = reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public ChargeForm() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.charge_form_id
     *
     * @return the value of hospital.charge_form.charge_form_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getChargeFormId() {
        return chargeFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.charge_form_id
     *
     * @param chargeFormId the value for hospital.charge_form.charge_form_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setChargeFormId(Integer chargeFormId) {
        this.chargeFormId = chargeFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.registration_id
     *
     * @return the value of hospital.charge_form.registration_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getRegistrationId() {
        return registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.registration_id
     *
     * @param registrationId the value for hospital.charge_form.registration_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setRegistrationId(Integer registrationId) {
        this.registrationId = registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.charge_item_id
     *
     * @return the value of hospital.charge_form.charge_item_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getChargeItemId() {
        return chargeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.charge_item_id
     *
     * @param chargeItemId the value for hospital.charge_form.charge_item_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setChargeItemId(Integer chargeItemId) {
        this.chargeItemId = chargeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.item_count
     *
     * @return the value of hospital.charge_form.item_count
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getItemCount() {
        return itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.item_count
     *
     * @param itemCount the value for hospital.charge_form.item_count
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.uncharged_nums
     *
     * @return the value of hospital.charge_form.uncharged_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getUnchargedNums() {
        return unchargedNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.uncharged_nums
     *
     * @param unchargedNums the value for hospital.charge_form.uncharged_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setUnchargedNums(Integer unchargedNums) {
        this.unchargedNums = unchargedNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.made_time
     *
     * @return the value of hospital.charge_form.made_time
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Date getMadeTime() {
        return madeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.made_time
     *
     * @param madeTime the value for hospital.charge_form.made_time
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setMadeTime(Date madeTime) {
        this.madeTime = madeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.valid
     *
     * @return the value of hospital.charge_form.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.valid
     *
     * @param valid the value for hospital.charge_form.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.department_id
     *
     * @return the value of hospital.charge_form.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.department_id
     *
     * @param departmentId the value for hospital.charge_form.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.doctor_id
     *
     * @return the value of hospital.charge_form.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.doctor_id
     *
     * @param doctorId the value for hospital.charge_form.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.collector_id
     *
     * @return the value of hospital.charge_form.collector_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getCollectorId() {
        return collectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.collector_id
     *
     * @param collectorId the value for hospital.charge_form.collector_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setCollectorId(Integer collectorId) {
        this.collectorId = collectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.not_given_nums
     *
     * @return the value of hospital.charge_form.not_given_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getNotGivenNums() {
        return notGivenNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.not_given_nums
     *
     * @param notGivenNums the value for hospital.charge_form.not_given_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setNotGivenNums(Integer notGivenNums) {
        this.notGivenNums = notGivenNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.reserve1
     *
     * @return the value of hospital.charge_form.reserve1
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.reserve1
     *
     * @param reserve1 the value for hospital.charge_form.reserve1
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.reserve2
     *
     * @return the value of hospital.charge_form.reserve2
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.reserve2
     *
     * @param reserve2 the value for hospital.charge_form.reserve2
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.charge_form.reserve3
     *
     * @return the value of hospital.charge_form.reserve3
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.charge_form.reserve3
     *
     * @param reserve3 the value for hospital.charge_form.reserve3
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }
}