package com.neusoft.medical.bean;

public class ConstantType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_type.constant_type_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer constantTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_type.constant_type_code
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String constantTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_type.constant_type_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String constantTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_type.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..constant_type
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public ConstantType(Integer constantTypeId, String constantTypeCode, String constantTypeName, Integer valid) {
        this.constantTypeId = constantTypeId;
        this.constantTypeCode = constantTypeCode;
        this.constantTypeName = constantTypeName;
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..constant_type
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public ConstantType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_type.constant_type_id
     *
     * @return the value of hospital..constant_type.constant_type_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getConstantTypeId() {
        return constantTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_type.constant_type_id
     *
     * @param constantTypeId the value for hospital..constant_type.constant_type_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setConstantTypeId(Integer constantTypeId) {
        this.constantTypeId = constantTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_type.constant_type_code
     *
     * @return the value of hospital..constant_type.constant_type_code
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getConstantTypeCode() {
        return constantTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_type.constant_type_code
     *
     * @param constantTypeCode the value for hospital..constant_type.constant_type_code
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setConstantTypeCode(String constantTypeCode) {
        this.constantTypeCode = constantTypeCode == null ? null : constantTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_type.constant_type_name
     *
     * @return the value of hospital..constant_type.constant_type_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getConstantTypeName() {
        return constantTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_type.constant_type_name
     *
     * @param constantTypeName the value for hospital..constant_type.constant_type_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setConstantTypeName(String constantTypeName) {
        this.constantTypeName = constantTypeName == null ? null : constantTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_type.valid
     *
     * @return the value of hospital..constant_type.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_type.valid
     *
     * @param valid the value for hospital..constant_type.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}