package com.neusoft.medical.bean;

public class ConstantItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_item.constant_item_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer constantItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_item.constant_type_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer constantTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_item.constant_code
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String constantCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_item.constant_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String constantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..constant_item.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..constant_item
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public ConstantItem(Integer constantItemId, Integer constantTypeId, String constantCode, String constantName, Integer valid) {
        this.constantItemId = constantItemId;
        this.constantTypeId = constantTypeId;
        this.constantCode = constantCode;
        this.constantName = constantName;
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..constant_item
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public ConstantItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_item.constant_item_id
     *
     * @return the value of hospital..constant_item.constant_item_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getConstantItemId() {
        return constantItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_item.constant_item_id
     *
     * @param constantItemId the value for hospital..constant_item.constant_item_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setConstantItemId(Integer constantItemId) {
        this.constantItemId = constantItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_item.constant_type_id
     *
     * @return the value of hospital..constant_item.constant_type_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getConstantTypeId() {
        return constantTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_item.constant_type_id
     *
     * @param constantTypeId the value for hospital..constant_item.constant_type_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setConstantTypeId(Integer constantTypeId) {
        this.constantTypeId = constantTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_item.constant_code
     *
     * @return the value of hospital..constant_item.constant_code
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getConstantCode() {
        return constantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_item.constant_code
     *
     * @param constantCode the value for hospital..constant_item.constant_code
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setConstantCode(String constantCode) {
        this.constantCode = constantCode == null ? null : constantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_item.constant_name
     *
     * @return the value of hospital..constant_item.constant_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getConstantName() {
        return constantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_item.constant_name
     *
     * @param constantName the value for hospital..constant_item.constant_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setConstantName(String constantName) {
        this.constantName = constantName == null ? null : constantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..constant_item.valid
     *
     * @return the value of hospital..constant_item.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..constant_item.valid
     *
     * @param valid the value for hospital..constant_item.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}