package com.neusoft.medical.bean;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.department_id
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.department_code
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.department_name
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.category
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.type
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.valid
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.reserve1
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.reserve2
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..department.reserve3
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    private String reserve3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..department
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public Department(Integer departmentId, String departmentCode, String departmentName, Integer category, Integer type, Integer valid, String reserve1, String reserve2, String reserve3) {
        this.departmentId = departmentId;
        this.departmentCode = departmentCode;
        this.departmentName = departmentName;
        this.category = category;
        this.type = type;
        this.valid = valid;
        this.reserve1 = reserve1;
        this.reserve2 = reserve2;
        this.reserve3 = reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..department
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public Department() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.department_id
     *
     * @return the value of hospital..department.department_id
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.department_id
     *
     * @param departmentId the value for hospital..department.department_id
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.department_code
     *
     * @return the value of hospital..department.department_code
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.department_code
     *
     * @param departmentCode the value for hospital..department.department_code
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.department_name
     *
     * @return the value of hospital..department.department_name
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.department_name
     *
     * @param departmentName the value for hospital..department.department_name
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.category
     *
     * @return the value of hospital..department.category
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.category
     *
     * @param category the value for hospital..department.category
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.type
     *
     * @return the value of hospital..department.type
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.type
     *
     * @param type the value for hospital..department.type
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.valid
     *
     * @return the value of hospital..department.valid
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.valid
     *
     * @param valid the value for hospital..department.valid
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.reserve1
     *
     * @return the value of hospital..department.reserve1
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.reserve1
     *
     * @param reserve1 the value for hospital..department.reserve1
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.reserve2
     *
     * @return the value of hospital..department.reserve2
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.reserve2
     *
     * @param reserve2 the value for hospital..department.reserve2
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..department.reserve3
     *
     * @return the value of hospital..department.reserve3
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..department.reserve3
     *
     * @param reserve3 the value for hospital..department.reserve3
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }
}