package com.neusoft.medical.bean;

public class Prescription {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.presciption_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer presciptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.registration_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer registrationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.registration_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String registrationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.doctor_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.reserve1
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.reserve2
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.reserve3
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital..prescription.content
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..prescription
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Prescription(Integer presciptionId, Integer registrationId, String registrationName, Integer doctorId, Integer valid, String reserve1, String reserve2, String reserve3, String content) {
        this.presciptionId = presciptionId;
        this.registrationId = registrationId;
        this.registrationName = registrationName;
        this.doctorId = doctorId;
        this.valid = valid;
        this.reserve1 = reserve1;
        this.reserve2 = reserve2;
        this.reserve3 = reserve3;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..prescription
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Prescription() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.presciption_id
     *
     * @return the value of hospital..prescription.presciption_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getPresciptionId() {
        return presciptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.presciption_id
     *
     * @param presciptionId the value for hospital..prescription.presciption_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setPresciptionId(Integer presciptionId) {
        this.presciptionId = presciptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.registration_id
     *
     * @return the value of hospital..prescription.registration_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getRegistrationId() {
        return registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.registration_id
     *
     * @param registrationId the value for hospital..prescription.registration_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setRegistrationId(Integer registrationId) {
        this.registrationId = registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.registration_name
     *
     * @return the value of hospital..prescription.registration_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getRegistrationName() {
        return registrationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.registration_name
     *
     * @param registrationName the value for hospital..prescription.registration_name
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setRegistrationName(String registrationName) {
        this.registrationName = registrationName == null ? null : registrationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.doctor_id
     *
     * @return the value of hospital..prescription.doctor_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.doctor_id
     *
     * @param doctorId the value for hospital..prescription.doctor_id
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.valid
     *
     * @return the value of hospital..prescription.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.valid
     *
     * @param valid the value for hospital..prescription.valid
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.reserve1
     *
     * @return the value of hospital..prescription.reserve1
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.reserve1
     *
     * @param reserve1 the value for hospital..prescription.reserve1
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.reserve2
     *
     * @return the value of hospital..prescription.reserve2
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.reserve2
     *
     * @param reserve2 the value for hospital..prescription.reserve2
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.reserve3
     *
     * @return the value of hospital..prescription.reserve3
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.reserve3
     *
     * @param reserve3 the value for hospital..prescription.reserve3
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital..prescription.content
     *
     * @return the value of hospital..prescription.content
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital..prescription.content
     *
     * @param content the value for hospital..prescription.content
     *
     * @mbggenerated Tue Jun 04 18:07:53 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}