package com.neusoft.medical.bean;

import java.util.Date;

public class SchedulingRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.scheduling_rule_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer schedulingRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.week_day
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String weekDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.department_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.doctor_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.type
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.period
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.limitation
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer limitation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.operator_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.operator_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_rule.operating_date
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Date operatingDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_rule
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public SchedulingRule(Integer schedulingRuleId, String weekDay, Integer departmentId, String departmentName, Integer doctorId, String doctorName, String type, Integer valid, String period, Integer limitation, Integer operatorId, String operatorName, Date operatingDate) {
        this.schedulingRuleId = schedulingRuleId;
        this.weekDay = weekDay;
        this.departmentId = departmentId;
        this.departmentName = departmentName;
        this.doctorId = doctorId;
        this.doctorName = doctorName;
        this.type = type;
        this.valid = valid;
        this.period = period;
        this.limitation = limitation;
        this.operatorId = operatorId;
        this.operatorName = operatorName;
        this.operatingDate = operatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_rule
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public SchedulingRule() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.scheduling_rule_id
     *
     * @return the value of hospital.scheduling_rule.scheduling_rule_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getSchedulingRuleId() {
        return schedulingRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.scheduling_rule_id
     *
     * @param schedulingRuleId the value for hospital.scheduling_rule.scheduling_rule_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setSchedulingRuleId(Integer schedulingRuleId) {
        this.schedulingRuleId = schedulingRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.week_day
     *
     * @return the value of hospital.scheduling_rule.week_day
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getWeekDay() {
        return weekDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.week_day
     *
     * @param weekDay the value for hospital.scheduling_rule.week_day
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setWeekDay(String weekDay) {
        this.weekDay = weekDay == null ? null : weekDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.department_id
     *
     * @return the value of hospital.scheduling_rule.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.department_id
     *
     * @param departmentId the value for hospital.scheduling_rule.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.department_name
     *
     * @return the value of hospital.scheduling_rule.department_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.department_name
     *
     * @param departmentName the value for hospital.scheduling_rule.department_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.doctor_id
     *
     * @return the value of hospital.scheduling_rule.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.doctor_id
     *
     * @param doctorId the value for hospital.scheduling_rule.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.doctor_name
     *
     * @return the value of hospital.scheduling_rule.doctor_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.doctor_name
     *
     * @param doctorName the value for hospital.scheduling_rule.doctor_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.type
     *
     * @return the value of hospital.scheduling_rule.type
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.type
     *
     * @param type the value for hospital.scheduling_rule.type
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.valid
     *
     * @return the value of hospital.scheduling_rule.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.valid
     *
     * @param valid the value for hospital.scheduling_rule.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.period
     *
     * @return the value of hospital.scheduling_rule.period
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.period
     *
     * @param period the value for hospital.scheduling_rule.period
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.limitation
     *
     * @return the value of hospital.scheduling_rule.limitation
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getLimitation() {
        return limitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.limitation
     *
     * @param limitation the value for hospital.scheduling_rule.limitation
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setLimitation(Integer limitation) {
        this.limitation = limitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.operator_id
     *
     * @return the value of hospital.scheduling_rule.operator_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.operator_id
     *
     * @param operatorId the value for hospital.scheduling_rule.operator_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.operator_name
     *
     * @return the value of hospital.scheduling_rule.operator_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.operator_name
     *
     * @param operatorName the value for hospital.scheduling_rule.operator_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_rule.operating_date
     *
     * @return the value of hospital.scheduling_rule.operating_date
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Date getOperatingDate() {
        return operatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_rule.operating_date
     *
     * @param operatingDate the value for hospital.scheduling_rule.operating_date
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setOperatingDate(Date operatingDate) {
        this.operatingDate = operatingDate;
    }
}