package com.neusoft.medical.bean;

import java.util.Date;

public class SchedulingInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.scheduling_info_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer schedulingInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.scheduling_time
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Date schedulingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.department_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.doctor_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.type
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.period
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.limitation
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer limitation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.scheduling_info.remian_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    private Integer remianNums;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public SchedulingInfo(Integer schedulingInfoId, Date schedulingTime, Integer departmentId, String departmentName, Integer doctorId, String doctorName, String type, Integer valid, String period, Integer limitation, Integer remianNums) {
        this.schedulingInfoId = schedulingInfoId;
        this.schedulingTime = schedulingTime;
        this.departmentId = departmentId;
        this.departmentName = departmentName;
        this.doctorId = doctorId;
        this.doctorName = doctorName;
        this.type = type;
        this.valid = valid;
        this.period = period;
        this.limitation = limitation;
        this.remianNums = remianNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public SchedulingInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.scheduling_info_id
     *
     * @return the value of hospital.scheduling_info.scheduling_info_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getSchedulingInfoId() {
        return schedulingInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.scheduling_info_id
     *
     * @param schedulingInfoId the value for hospital.scheduling_info.scheduling_info_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setSchedulingInfoId(Integer schedulingInfoId) {
        this.schedulingInfoId = schedulingInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.scheduling_time
     *
     * @return the value of hospital.scheduling_info.scheduling_time
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Date getSchedulingTime() {
        return schedulingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.scheduling_time
     *
     * @param schedulingTime the value for hospital.scheduling_info.scheduling_time
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setSchedulingTime(Date schedulingTime) {
        this.schedulingTime = schedulingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.department_id
     *
     * @return the value of hospital.scheduling_info.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.department_id
     *
     * @param departmentId the value for hospital.scheduling_info.department_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.department_name
     *
     * @return the value of hospital.scheduling_info.department_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.department_name
     *
     * @param departmentName the value for hospital.scheduling_info.department_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.doctor_id
     *
     * @return the value of hospital.scheduling_info.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.doctor_id
     *
     * @param doctorId the value for hospital.scheduling_info.doctor_id
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.doctor_name
     *
     * @return the value of hospital.scheduling_info.doctor_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.doctor_name
     *
     * @param doctorName the value for hospital.scheduling_info.doctor_name
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.type
     *
     * @return the value of hospital.scheduling_info.type
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.type
     *
     * @param type the value for hospital.scheduling_info.type
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.valid
     *
     * @return the value of hospital.scheduling_info.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.valid
     *
     * @param valid the value for hospital.scheduling_info.valid
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.period
     *
     * @return the value of hospital.scheduling_info.period
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.period
     *
     * @param period the value for hospital.scheduling_info.period
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.limitation
     *
     * @return the value of hospital.scheduling_info.limitation
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getLimitation() {
        return limitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.limitation
     *
     * @param limitation the value for hospital.scheduling_info.limitation
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setLimitation(Integer limitation) {
        this.limitation = limitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.scheduling_info.remian_nums
     *
     * @return the value of hospital.scheduling_info.remian_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public Integer getRemianNums() {
        return remianNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.scheduling_info.remian_nums
     *
     * @param remianNums the value for hospital.scheduling_info.remian_nums
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    public void setRemianNums(Integer remianNums) {
        this.remianNums = remianNums;
    }
}