package com.neusoft.medical.dao;

import com.neusoft.medical.bean.Account;
import com.neusoft.medical.bean.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    @Delete({
        "delete from hospital..account",
        "where account_id = #{accountId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    @Insert({
        "insert into hospital..account (account_id, user_name, ",
        "user_password, valid, ",
        "reserve1, reserve2, ",
        "reserve3)",
        "values (#{accountId,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{userPassword,jdbcType=VARCHAR}, #{valid,jdbcType=INTEGER}, ",
        "#{reserve1,jdbcType=VARCHAR}, #{reserve2,jdbcType=VARCHAR}, ",
        "#{reserve3,jdbcType=VARCHAR})"
    })
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    @Select({
        "select",
        "account_id, user_name, user_password, valid, reserve1, reserve2, reserve3",
        "from hospital..account",
        "where account_id = #{accountId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Account selectByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..account
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    @Update({
        "update hospital..account",
        "set user_name = #{userName,jdbcType=VARCHAR},",
          "user_password = #{userPassword,jdbcType=VARCHAR},",
          "valid = #{valid,jdbcType=INTEGER},",
          "reserve1 = #{reserve1,jdbcType=VARCHAR},",
          "reserve2 = #{reserve2,jdbcType=VARCHAR},",
          "reserve3 = #{reserve3,jdbcType=VARCHAR}",
        "where account_id = #{accountId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Account record);
}