package com.neusoft.medical.dao;

import com.neusoft.medical.bean.ChargeForm;
import com.neusoft.medical.bean.ChargeFormExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface ChargeFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    long countByExample(ChargeFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int deleteByExample(ChargeFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Delete({
        "delete from hospital.charge_form",
        "where charge_form_id = #{chargeFormId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer chargeFormId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Insert({
        "insert into hospital.charge_form (charge_form_id, registration_id, ",
        "charge_item_id, item_count, ",
        "uncharged_nums, made_time, ",
        "valid, department_id, ",
        "doctor_id, collector_id, ",
        "not_given_nums, reserve1, ",
        "reserve2, reserve3)",
        "values (#{chargeFormId,jdbcType=INTEGER}, #{registrationId,jdbcType=INTEGER}, ",
        "#{chargeItemId,jdbcType=INTEGER}, #{itemCount,jdbcType=INTEGER}, ",
        "#{unchargedNums,jdbcType=INTEGER}, #{madeTime,jdbcType=TIMESTAMP}, ",
        "#{valid,jdbcType=INTEGER}, #{departmentId,jdbcType=INTEGER}, ",
        "#{doctorId,jdbcType=INTEGER}, #{collectorId,jdbcType=INTEGER}, ",
        "#{notGivenNums,jdbcType=INTEGER}, #{reserve1,jdbcType=VARCHAR}, ",
        "#{reserve2,jdbcType=VARCHAR}, #{reserve3,jdbcType=VARCHAR})"
    })
    int insert(ChargeForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int insertSelective(ChargeForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    List<ChargeForm> selectByExample(ChargeFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Select({
        "select",
        "charge_form_id, registration_id, charge_item_id, item_count, uncharged_nums, ",
        "made_time, valid, department_id, doctor_id, collector_id, not_given_nums, reserve1, ",
        "reserve2, reserve3",
        "from hospital.charge_form",
        "where charge_form_id = #{chargeFormId,jdbcType=INTEGER}"
    })
    @ResultMap("com.neusoft.medical.dao1.ChargeFormMapper.BaseResultMap")
    ChargeForm selectByPrimaryKey(Integer chargeFormId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChargeForm record, @Param("example") ChargeFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByExample(@Param("record") ChargeForm record, @Param("example") ChargeFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByPrimaryKeySelective(ChargeForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.charge_form
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Update({
        "update hospital.charge_form",
        "set registration_id = #{registrationId,jdbcType=INTEGER},",
          "charge_item_id = #{chargeItemId,jdbcType=INTEGER},",
          "item_count = #{itemCount,jdbcType=INTEGER},",
          "uncharged_nums = #{unchargedNums,jdbcType=INTEGER},",
          "made_time = #{madeTime,jdbcType=TIMESTAMP},",
          "valid = #{valid,jdbcType=INTEGER},",
          "department_id = #{departmentId,jdbcType=INTEGER},",
          "doctor_id = #{doctorId,jdbcType=INTEGER},",
          "collector_id = #{collectorId,jdbcType=INTEGER},",
          "not_given_nums = #{notGivenNums,jdbcType=INTEGER},",
          "reserve1 = #{reserve1,jdbcType=VARCHAR},",
          "reserve2 = #{reserve2,jdbcType=VARCHAR},",
          "reserve3 = #{reserve3,jdbcType=VARCHAR}",
        "where charge_form_id = #{chargeFormId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ChargeForm record);
}