package com.neusoft.medical.dao;

import com.neusoft.medical.bean1.ConstantItem;
import com.neusoft.medical.bean1.ConstantItemExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface ConstantItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    long countByExample(ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int deleteByExample(ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Delete({
        "delete from hospital.constant_item",
        "where constant_item_id = #{constantItemId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer constantItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Insert({
        "insert into hospital.constant_item (constant_item_id, constant_type_id, ",
        "constant_code, constant_name, ",
        "valid)",
        "values (#{constantItemId,jdbcType=INTEGER}, #{constantTypeId,jdbcType=INTEGER}, ",
        "#{constantCode,jdbcType=VARCHAR}, #{constantName,jdbcType=VARCHAR}, ",
        "#{valid,jdbcType=INTEGER})"
    })
    int insert(ConstantItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int insertSelective(ConstantItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    List<ConstantItem> selectByExample(ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Select({
        "select",
        "constant_item_id, constant_type_id, constant_code, constant_name, valid",
        "from hospital.constant_item",
        "where constant_item_id = #{constantItemId,jdbcType=INTEGER}"
    })
    @ResultMap("com.neusoft.medical.dao1.ConstantItemMapper.BaseResultMap")
    ConstantItem selectByPrimaryKey(Integer constantItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") ConstantItem record, @Param("example") ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByExample(@Param("record") ConstantItem record, @Param("example") ConstantItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByPrimaryKeySelective(ConstantItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.constant_item
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Update({
        "update hospital.constant_item",
        "set constant_type_id = #{constantTypeId,jdbcType=INTEGER},",
          "constant_code = #{constantCode,jdbcType=VARCHAR},",
          "constant_name = #{constantName,jdbcType=VARCHAR},",
          "valid = #{valid,jdbcType=INTEGER}",
        "where constant_item_id = #{constantItemId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ConstantItem record);
}