package com.neusoft.medical.dao;

import com.neusoft.medical.bean1.Doctor;
import com.neusoft.medical.bean1.DoctorExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    long countByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int deleteByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Delete({
        "delete from hospital.doctor",
        "where doctor_id = #{doctorId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Insert({
        "insert into hospital.doctor (doctor_id, doctor_name, ",
        "department, type, ",
        "job_title, account_id, ",
        "valid, doctor_scheduling, ",
        "reserve1, reserve2, ",
        "reserve3)",
        "values (#{doctorId,jdbcType=INTEGER}, #{doctorName,jdbcType=VARCHAR}, ",
        "#{department,jdbcType=INTEGER}, #{type,jdbcType=INTEGER}, ",
        "#{jobTitle,jdbcType=VARCHAR}, #{accountId,jdbcType=INTEGER}, ",
        "#{valid,jdbcType=INTEGER}, #{doctorScheduling,jdbcType=INTEGER}, ",
        "#{reserve1,jdbcType=VARCHAR}, #{reserve2,jdbcType=VARCHAR}, ",
        "#{reserve3,jdbcType=VARCHAR})"
    })
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int insertSelective(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    List<Doctor> selectByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Select({
        "select",
        "doctor_id, doctor_name, department, type, job_title, account_id, valid, doctor_scheduling, ",
        "reserve1, reserve2, reserve3",
        "from hospital.doctor",
        "where doctor_id = #{doctorId,jdbcType=INTEGER}"
    })
    @ResultMap("com.neusoft.medical.dao1.DoctorMapper.BaseResultMap")
    Doctor selectByPrimaryKey(Integer doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Doctor record, @Param("example") DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByExample(@Param("record") Doctor record, @Param("example") DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByPrimaryKeySelective(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.doctor
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Update({
        "update hospital.doctor",
        "set doctor_name = #{doctorName,jdbcType=VARCHAR},",
          "department = #{department,jdbcType=INTEGER},",
          "type = #{type,jdbcType=INTEGER},",
          "job_title = #{jobTitle,jdbcType=VARCHAR},",
          "account_id = #{accountId,jdbcType=INTEGER},",
          "valid = #{valid,jdbcType=INTEGER},",
          "doctor_scheduling = #{doctorScheduling,jdbcType=INTEGER},",
          "reserve1 = #{reserve1,jdbcType=VARCHAR},",
          "reserve2 = #{reserve2,jdbcType=VARCHAR},",
          "reserve3 = #{reserve3,jdbcType=VARCHAR}",
        "where doctor_id = #{doctorId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Doctor record);
}