package com.neusoft.medical.dao;

import com.neusoft.medical.bean.Patient;
import com.neusoft.medical.bean.PatientExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int deleteByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    @Delete({
        "delete from hospital..patient",
        "where patient_id = #{patientId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    @Insert({
        "insert into hospital..patient (patient_id, patient_name, ",
        "birth_date, allergies, ",
        "identify_card_no, social_security_card_no, ",
        "family_address, alive, ",
        "gender, reserve1, reserve2, ",
        "reserve3)",
        "values (#{patientId,jdbcType=INTEGER}, #{patientName,jdbcType=VARCHAR}, ",
        "#{birthDate,jdbcType=DATE}, #{allergies,jdbcType=VARCHAR}, ",
        "#{identifyCardNo,jdbcType=BIGINT}, #{socialSecurityCardNo,jdbcType=VARCHAR}, ",
        "#{familyAddress,jdbcType=VARCHAR}, #{alive,jdbcType=INTEGER}, ",
        "#{gender,jdbcType=CHAR}, #{reserve1,jdbcType=VARCHAR}, #{reserve2,jdbcType=VARCHAR}, ",
        "#{reserve3,jdbcType=VARCHAR})"
    })
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    List<Patient> selectByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    @Select({
        "select",
        "patient_id, patient_name, birth_date, allergies, identify_card_no, social_security_card_no, ",
        "family_address, alive, gender, reserve1, reserve2, reserve3",
        "from hospital..patient",
        "where patient_id = #{patientId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Patient selectByPrimaryKey(Integer patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int updateByExample(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    int updateByPrimaryKeySelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..patient
     *
     * @mbggenerated Tue Jun 04 11:21:04 CST 2019
     */
    @Update({
        "update hospital..patient",
        "set patient_name = #{patientName,jdbcType=VARCHAR},",
          "birth_date = #{birthDate,jdbcType=DATE},",
          "allergies = #{allergies,jdbcType=VARCHAR},",
          "identify_card_no = #{identifyCardNo,jdbcType=BIGINT},",
          "social_security_card_no = #{socialSecurityCardNo,jdbcType=VARCHAR},",
          "family_address = #{familyAddress,jdbcType=VARCHAR},",
          "alive = #{alive,jdbcType=INTEGER},",
          "gender = #{gender,jdbcType=CHAR},",
          "reserve1 = #{reserve1,jdbcType=VARCHAR},",
          "reserve2 = #{reserve2,jdbcType=VARCHAR},",
          "reserve3 = #{reserve3,jdbcType=VARCHAR}",
        "where patient_id = #{patientId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Patient record);
}