package com.neusoft.medical.dao;

import com.neusoft.medical.bean1.SchedulingInfo;
import com.neusoft.medical.bean1.SchedulingInfoExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface SchedulingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    long countByExample(SchedulingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int deleteByExample(SchedulingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Delete({
        "delete from hospital.scheduling_info",
        "where scheduling_info_id = #{schedulingInfoId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer schedulingInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Insert({
        "insert into hospital.scheduling_info (scheduling_info_id, scheduling_time, ",
        "department_id, department_name, ",
        "doctor_id, doctor_name, ",
        "type, valid, period, ",
        "limitation, remian_nums)",
        "values (#{schedulingInfoId,jdbcType=INTEGER}, #{schedulingTime,jdbcType=DATE}, ",
        "#{departmentId,jdbcType=INTEGER}, #{departmentName,jdbcType=VARCHAR}, ",
        "#{doctorId,jdbcType=INTEGER}, #{doctorName,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{valid,jdbcType=INTEGER}, #{period,jdbcType=VARCHAR}, ",
        "#{limitation,jdbcType=INTEGER}, #{remianNums,jdbcType=INTEGER})"
    })
    int insert(SchedulingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int insertSelective(SchedulingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    List<SchedulingInfo> selectByExample(SchedulingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Select({
        "select",
        "scheduling_info_id, scheduling_time, department_id, department_name, doctor_id, ",
        "doctor_name, type, valid, period, limitation, remian_nums",
        "from hospital.scheduling_info",
        "where scheduling_info_id = #{schedulingInfoId,jdbcType=INTEGER}"
    })
    @ResultMap("com.neusoft.medical.dao1.SchedulingInfoMapper.BaseResultMap")
    SchedulingInfo selectByPrimaryKey(Integer schedulingInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") SchedulingInfo record, @Param("example") SchedulingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByExample(@Param("record") SchedulingInfo record, @Param("example") SchedulingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    int updateByPrimaryKeySelective(SchedulingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital.scheduling_info
     *
     * @mbg.generated Mon Jun 10 18:44:57 CST 2019
     */
    @Update({
        "update hospital.scheduling_info",
        "set scheduling_time = #{schedulingTime,jdbcType=DATE},",
          "department_id = #{departmentId,jdbcType=INTEGER},",
          "department_name = #{departmentName,jdbcType=VARCHAR},",
          "doctor_id = #{doctorId,jdbcType=INTEGER},",
          "doctor_name = #{doctorName,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "valid = #{valid,jdbcType=INTEGER},",
          "period = #{period,jdbcType=VARCHAR},",
          "limitation = #{limitation,jdbcType=INTEGER},",
          "remian_nums = #{remianNums,jdbcType=INTEGER}",
        "where scheduling_info_id = #{schedulingInfoId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SchedulingInfo record);
}