package com.neusoft.medical.dao;

import com.neusoft.medical.bean.UserRights;
import com.neusoft.medical.bean.UserRightsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserRightsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    int countByExample(UserRightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    int deleteByExample(UserRightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    @Delete({
        "delete from hospital..user_rights",
        "where user_rights_id = #{userRightsId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userRightsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    @Insert({
        "insert into hospital..user_rights (user_rights_id, user_id, ",
        "right_id)",
        "values (#{userRightsId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{rightId,jdbcType=INTEGER})"
    })
    int insert(UserRights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    int insertSelective(UserRights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    List<UserRights> selectByExample(UserRightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    @Select({
        "select",
        "user_rights_id, user_id, right_id",
        "from hospital..user_rights",
        "where user_rights_id = #{userRightsId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserRights selectByPrimaryKey(Integer userRightsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserRights record, @Param("example") UserRightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    int updateByExample(@Param("record") UserRights record, @Param("example") UserRightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    int updateByPrimaryKeySelective(UserRights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital..user_rights
     *
     * @mbggenerated Wed Jun 05 11:28:51 CST 2019
     */
    @Update({
        "update hospital..user_rights",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "right_id = #{rightId,jdbcType=INTEGER}",
        "where user_rights_id = #{userRightsId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserRights record);
}